version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

volumes:
  postgres_data: